name: Create New Repository
on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Owner of the new repository'
        required: true
      repo-name:
        description: 'Name of the new repository'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Create Repository
      uses: actions/create-repository@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ github.event.inputs.repo-name }}
        description: 'New repository created with GitHub Actions'
        private: false
        auto_init: true
